skip-check:
  # LRS acceptable for dev/test environments; GRS used in production
  - CKV_AZURE_206
  # Shared key access required for Terraform provider limitations
  # Access controlled via RBAC and private endpoints
  - CKV2_AZURE_40
  # False positive: Logging IS enabled via azurerm_monitor_diagnostic_setting
  # See: azurerm_monitor_diagnostic_setting.evidence_blob_logging
  - CKV2_AZURE_21
  # Queue service logging - not using queue service in this deployment
  - CKV_AZURE_33