skip-check:
  - CKV2_AZURE_21  # Blob read/write/delete logging is enforced via azurerm_monitor_diagnostic_setting on the storage account; classic blob logging is deprecated and not configurable here.
